"""Tests for Task Retry on Fail (TC-02 from Section 7).

Scenario: Task retry on fail (TC-02 from Section 7)
Given Ralph is on task N
And scenario signal is { "pass": false }
When Ralph processes the signal
Then Ralph retries task N with fresh context
And retry count for task N is incremented

These tests verify Ralph.process_signal() correctly handles fail signals.
"""

import json
from pathlib import Path
from unittest.mock import patch

import pytest

from src.plan import ImplementationPlan, Task
from src.signal import Signal


class TestTaskRetryOnFail:
    """Tests for TC-02: Task retry when signal is { "pass": false }."""

    @pytest.fixture
    def ralph_with_plan(self, tmp_path):
        """Create Ralph instance with a plan containing a task."""
        from src.ralph import Ralph
        from harness.state_manager import RETRY_STATE_FILE

        # Clear state file to ensure test isolation
        if RETRY_STATE_FILE.exists():
            RETRY_STATE_FILE.unlink()

        # Create temporary plan file
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test Project

## Tasks

- [ ] **Task One** (T001)
  Description for task one
- [ ] **Task Two** (T002)
  Description for task two

---
*Auto-generated by Ralph Dark Factory*
""")

        # Patch IMPLEMENTATION_PLAN path
        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            return ralph

    def test_process_signal_increments_retry_count_on_fail(
        self, ralph_with_plan, temp_signal_path
    ):
        """When signal is { "pass": false }, retry count is incremented."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan
            current_task = ralph.get_current_task()
            assert current_task is not None
            assert current_task.id == "T001"
            assert current_task.retry_count == 0

            # Write fail signal
            temp_signal_path.write_text('{"pass": false}')

            # Load signal into Ralph
            ralph.load_signal()
            assert ralph.signal.pass_result is False

            # Process signal - should increment retry count
            ralph.process_signal()

            # Verify retry count was incremented
            assert current_task.retry_count == 1, "Retry count should be 1 after first failure"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_process_signal_does_not_mark_done_on_fail(
        self, ralph_with_plan, temp_signal_path
    ):
        """When signal is { "pass": false }, task is NOT marked done."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan
            current_task = ralph.get_current_task()
            assert current_task.status == "pending"

            # Write fail signal
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()

            # Task should still be pending (not done)
            assert current_task.status == "pending", "Task should NOT be marked done on fail"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_process_signal_keeps_same_task_on_fail(
        self, ralph_with_plan, temp_signal_path
    ):
        """When signal is { "pass": false }, Ralph retries the same task."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan

            # Verify initial current task is T001
            current = ralph.get_current_task()
            assert current.id == "T001"

            # Write fail signal
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()

            # After processing, current task should still be T001 (retry)
            next_task = ralph.get_current_task()
            assert next_task is not None, "There should still be a current task"
            assert next_task.id == "T001", "Same task should be retried after fail"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_multiple_fails_increment_retry_count(
        self, ralph_with_plan, temp_signal_path
    ):
        """Multiple fail signals increment retry count each time."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan

            # First fail
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task().retry_count == 1

            # Second fail
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task().retry_count == 2

            # Third fail
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task().retry_count == 3
        finally:
            Signal.SIGNAL_PATH = original_signal_path


class TestRetryCountPersistence:
    """Tests for TC-04: Retry count persistence across restarts."""

    def test_retry_count_persists_to_state_manager(self, tmp_path):
        """Retry count should be written to harness state manager."""
        from src.ralph import Ralph

        # Patch both plan and state manager paths
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        state_file = tmp_path / "retry_state.json"

        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        # Patch paths
        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            with patch("harness.state_manager.RETRY_STATE_FILE", state_file):
                ralph = Ralph(project_path=str(tmp_path))
                ralph.load_plan()

                # Get current task
                current_task = ralph.get_current_task()
                assert current_task.id == "T001"

                # Write fail signal
                signal_path = tmp_path / "signal.json"
                Signal.SIGNAL_PATH = signal_path
                try:
                    signal_path.write_text('{"pass": false}')

                    ralph.load_signal()
                    ralph.process_signal()

                    # Check state manager file was updated
                    assert state_file.exists(), "State file should be created"
                    state = json.loads(state_file.read_text())
                    assert "T001" in state, "Task ID should be in state"
                    assert state["T001"] == 1, "Retry count should be 1"
                finally:
                    Signal.SIGNAL_PATH = Path("/tmp/ralph-scenario-result.json")

    def test_retry_count_persists_across_ralph_restart(self, tmp_path):
        """Retry count should survive Ralph process restart."""
        from src.ralph import Ralph
        import harness.state_manager as sm

        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        state_file = tmp_path / "retry_state.json"

        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            with patch("harness.state_manager.RETRY_STATE_FILE", state_file):
                signal_path = tmp_path / "signal.json"
                Signal.SIGNAL_PATH = signal_path

                try:
                    # First Ralph instance
                    ralph1 = Ralph(project_path=str(tmp_path))
                    ralph1.load_plan()

                    # Fail twice
                    for _ in range(2):
                        signal_path.write_text('{"pass": false}')
                        ralph1.load_signal()
                        ralph1.process_signal()

                    # Verify state was persisted
                    assert state_file.exists()
                    state = json.loads(state_file.read_text())
                    assert state.get("T001") == 2, "State should have retry count 2"

                    # Create new Ralph instance (simulating restart)
                    ralph2 = Ralph(project_path=str(tmp_path))
                    ralph2.load_plan()

                    # Verify retry count was loaded from state
                    current = ralph2.get_current_task()
                    assert current.id == "T001"
                    # The plan's retry count should reflect persisted state
                    # This test documents that plan.retry_count should sync with state
                finally:
                    Signal.SIGNAL_PATH = Path("/tmp/ralph-scenario-result.json")


class TestPlanRetryIncrement:
    """Tests for plan.increment_retry functionality used by process_signal."""

    def test_increment_retry_returns_new_count(self, tmp_path):
        """increment_retry returns the new count after incrementing."""
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            plan = ImplementationPlan(project_name="Test")
            plan.add_task("Task One", "Description")

            # First increment
            count1 = plan.increment_retry("T001")
            assert count1 == 1

            # Second increment
            count2 = plan.increment_retry("T001")
            assert count2 == 2

    def test_increment_retry_updates_task_retry_count(self, tmp_path):
        """increment_retry updates the task's retry_count attribute."""
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            plan = ImplementationPlan(project_name="Test")
            task = plan.add_task("Task One", "Description")

            assert task.retry_count == 0

            plan.increment_retry("T001")
            assert task.retry_count == 1

            plan.increment_retry("T001")
            assert task.retry_count == 2

    def test_increment_retry_nonexistent_task_returns_zero(self, tmp_path):
        """increment_retry returns 0 for nonexistent task ID."""
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            plan = ImplementationPlan(project_name="Test")
            plan.add_task("Task One", "Description")

            count = plan.increment_retry("T999")  # Non-existent
            assert count == 0


class TestRalphProcessFailIntegration:
    """Integration tests for Ralph.process_signal with fail signal."""

    @pytest.fixture
    def ralph_with_tasks(self, tmp_path):
        """Create Ralph with a multi-task plan."""
        from src.ralph import Ralph

        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Integration Test

## Tasks

- [ ] **Health Check** (T001)
  Check system health
- [ ] **API Status** (T002)
  Check API status

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            return ralph

    def test_integration_fail_signal_keeps_task(
        self, ralph_with_tasks, temp_signal_path
    ):
        """Full integration: fail signal -> retry same task."""
        from src.ralph import Ralph

        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_tasks

            # Step 1: Verify starting at T001
            task = ralph.get_current_task()
            assert task.id == "T001"

            # Step 2: Write fail signal to file
            with open(temp_signal_path, "w") as f:
                json.dump({"pass": False}, f)

            # Step 3: Ralph reads signal
            ralph.load_signal()
            assert ralph.signal.pass_result is False

            # Step 4: Ralph processes signal
            ralph.process_signal()

            # Step 5: Verify T001 is still current (retry)
            new_task = ralph.get_current_task()
            assert new_task.id == "T001", "Should retry same task after fail"

            # Step 6: Verify retry count was incremented
            assert new_task.retry_count == 1, "Retry count should be 1"

            # Step 7: Verify T001 is NOT marked done
            t001 = next((t for t in ralph.plan.tasks if t.id == "T001"), None)
            assert t001.status == "pending", "Task should still be pending"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_integration_fail_signal_does_not_advance(
        self, ralph_with_tasks, temp_signal_path
    ):
        """Fail signal should NOT advance to next task."""
        from src.ralph import Ralph

        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_tasks

            # Write fail signal
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()

            # Should still be on T001, NOT T002
            new_task = ralph.get_current_task()
            assert new_task.id == "T001", "Should NOT advance to T002 on fail"
        finally:
            Signal.SIGNAL_PATH = original_signal_path
