"""Tests for Task Advancement on Pass (TC-01 from Section 7).

Scenario: Given Ralph is on task N AND scenario signal is { "pass": true }
When Ralph processes the signal
Then task N is marked done in IMPLEMENTATION_PLAN.md
AND Ralph picks task N+1 for the next iteration

These tests verify Ralph.process_signal() correctly advances tasks.
"""

import json
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

from src.plan import ImplementationPlan, Task
from src.signal import Signal


class TestTaskAdvancementOnPass:
    """Tests for TC-01: Task advancement when signal is { "pass": true }."""

    @pytest.fixture
    def ralph_with_plan(self, tmp_path):
        """Create Ralph instance with a plan containing multiple tasks."""
        from src.ralph import Ralph

        # Create temporary plan file - must use format load_plan expects: - [ ] / - [x]
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test Project

## Tasks

- [ ] **Task One** (T001)
  Description for task one
- [ ] **Task Two** (T002)
  Description for task two
- [ ] **Task Three** (T003)
  Description for task three

---
*Auto-generated by Ralph Dark Factory*
""")

        # Patch IMPLEMENTATION_PLAN path
        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            return ralph

    def test_process_signal_marks_current_task_done_on_pass(
        self, ralph_with_plan, temp_signal_path
    ):
        """When signal is { "pass": true }, current task is marked done."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            # Setup: Ralph is on task N (first pending task)
            ralph = ralph_with_plan
            current_task = ralph.get_current_task()
            assert current_task is not None
            assert current_task.id == "T001"
            assert current_task.status == "pending"

            # Write pass signal
            temp_signal_path.write_text('{"pass": true}')

            # Load signal into Ralph
            ralph.load_signal()
            assert ralph.signal.pass_result is True

            # Process signal - should mark task T001 as done
            ralph.process_signal()

            # Verify task T001 is now done (check plan object directly)
            done_task = next((t for t in ralph.plan.tasks if t.id == "T001"), None)
            assert done_task is not None
            assert done_task.status == "done", "Task T001 should be marked done"
            
            # Also verify T002 is now the current task (advancement)
            assert ralph.plan.get_current_task().id == "T002"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_process_signal_advances_to_next_task_on_pass(
        self, ralph_with_plan, temp_signal_path
    ):
        """When signal is { "pass": true }, Ralph picks task N+1 next."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan

            # Verify initial current task is T001
            current = ralph.get_current_task()
            assert current.id == "T001"

            # Write pass signal
            temp_signal_path.write_text('{"pass": true}')
            ralph.load_signal()
            ralph.process_signal()

            # After processing, get_current_task should return T002
            next_task = ralph.get_current_task()
            assert next_task is not None, "There should be a next task (T002)"
            assert next_task.id == "T002", "Next task should be T002"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_multiple_passes_advance_through_all_tasks(
        self, ralph_with_plan, temp_signal_path
    ):
        """Multiple pass signals advance through all tasks sequentially."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_plan

            # First pass: should complete T001, advance to T002
            temp_signal_path.write_text('{"pass": true}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task().id == "T002"

            # Second pass: should complete T002, advance to T003
            temp_signal_path.write_text('{"pass": true}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task().id == "T003"

            # Third pass: should complete T003, no more tasks
            temp_signal_path.write_text('{"pass": true}')
            ralph.load_signal()
            ralph.process_signal()
            assert ralph.get_current_task() is None, "No more tasks after T003"
        finally:
            Signal.SIGNAL_PATH = original_signal_path


class TestPlanMarking:
    """Tests for plan.mark_done functionality used by process_signal."""

    def test_mark_done_updates_task_status(self, tmp_path):
        """mark_done changes task status from pending to done."""
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **First Task** (T001)
  Description

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            plan = ImplementationPlan(project_name="Test")
            plan.add_task("First Task", "Description")

            # Before mark_done
            assert plan.tasks[0].status == "pending"

            # Mark done
            plan.mark_done("T001")

            # After mark_done
            assert plan.tasks[0].status == "done"

    def test_mark_done_saves_to_file(self, tmp_path):
        """mark_done persists the change to IMPLEMENTATION_PLAN.md."""
        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Test

## Tasks

- [ ] **Task One** (T001)
  Description

---
*Auto-generated*
""")

        # Use context manager to keep patch active for load_plan call
        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            plan = ImplementationPlan(project_name="Test")
            plan.add_task("Task One", "Description")

            plan.mark_done("T001")

            # Reload from file and verify (still inside patch context)
            from src.plan import load_plan
            reloaded_plan = load_plan()
            assert reloaded_plan.tasks[0].status == "done"


class TestGetCurrentTask:
    """Tests for get_current_task behavior."""

    def test_get_current_task_returns_first_pending(self):
        """get_current_task returns the first task with pending status."""
        plan = ImplementationPlan(project_name="Test")
        task1 = plan.add_task("Task 1", "Desc 1")
        task2 = plan.add_task("Task 2", "Desc 2")
        task3 = plan.add_task("Task 3", "Desc 3")

        # Mark first task as done
        task1.status = "done"

        # Should return T002
        current = plan.get_current_task()
        assert current == task2
        assert current.id == "T002"

    def test_get_current_task_returns_none_when_all_done(self):
        """get_current_task returns None when all tasks are done."""
        plan = ImplementationPlan(project_name="Test")
        plan.add_task("Task 1", "Desc 1")
        plan.add_task("Task 2", "Desc 2")

        for task in plan.tasks:
            task.status = "done"

        current = plan.get_current_task()
        assert current is None


class TestRalphProcessSignalIntegration:
    """Integration tests for Ralph.process_signal with real signal file."""

    @pytest.fixture
    def ralph_with_tasks(self, tmp_path):
        """Create Ralph with a multi-task plan."""
        from src.ralph import Ralph

        plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
        plan_file.write_text("""# Implementation Plan: Integration Test

## Tasks

- [ ] **Health Check** (T001)
  Check system health
- [ ] **API Status** (T002)
  Check API status

---
*Auto-generated*
""")

        with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            return ralph

    def test_integration_pass_signal_advances_task(
        self, ralph_with_tasks, temp_signal_path
    ):
        """Full integration: pass signal -> mark done -> advance to next."""
        from src.ralph import Ralph

        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_tasks

            # Step 1: Verify starting at T001
            task = ralph.get_current_task()
            assert task.id == "T001"

            # Step 2: Write pass signal to file (simulating harness result)
            with open(temp_signal_path, "w") as f:
                json.dump({"pass": True}, f)

            # Step 3: Ralph reads signal
            ralph.load_signal()
            assert ralph.signal.pass_result is True

            # Step 4: Ralph processes signal
            ralph.process_signal()

            # Step 5: Verify T001 is done and T002 is current
            new_task = ralph.get_current_task()
            assert new_task.id == "T002"

            # Verify T001 status changed
            t001 = next((t for t in ralph.plan.tasks if t.id == "T001"), None)
            assert t001.status == "done"
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_integration_signal_file_content_after_mark_done(
        self, ralph_with_tasks, temp_signal_path
    ):
        """After processing pass, plan file shows task done."""
        from src.ralph import Ralph

        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        plan_file = ralph_with_tasks.plan.tasks[0].id  # dummy

        try:
            ralph = ralph_with_tasks

            # Process pass signal
            temp_signal_path.write_text('{"pass": true}')
            ralph.load_signal()
            ralph.process_signal()

            # Check plan file content - should use [x] format, not [[x]]
            plan_path = Path("IMPLEMENTATION_PLAN.md")
            if plan_path.exists():
                content = plan_path.read_text()
                # Should contain [x] for T001 (done)
                assert "[x]" in content
        finally:
            Signal.SIGNAL_PATH = original_signal_path