"""Tests for Spinning Detection (TC-03 from Section 7).

Scenario: Spinning detection (TC-03 from Section 7)
Given Ralph has retried task N 5 times
And each time scenario signal was { "pass": false }
When Ralph processes the 5th failure signal
Then Ralph writes { "spinning": true, "task": "task-N-description" }
And the operator is notified to intervene

These tests verify Ralph.process_signal() correctly detects spinning
after 5 consecutive failures and writes the spinning signal.
"""

import json
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from src.plan import ImplementationPlan, Task
from src.signal import Signal


@pytest.fixture
def clean_state():
    """Ensure clean state before each test."""
    # Reset Signal class attribute
    original_signal_path = Signal.SIGNAL_PATH
    Signal.SIGNAL_PATH = None
    
    yield
    
    # Cleanup: reset to original state
    Signal.SIGNAL_PATH = original_signal_path


@pytest.fixture
def ralph_with_task(tmp_path, temp_signal_path, clean_state):
    """Create Ralph instance with a single task."""
    from src.ralph import Ralph

    # Create temporary plan file with one task
    plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
    plan_file.write_text("""# Implementation Plan: Spinning Test

## Tasks

- [ ] **Implement Feature X** (T001)
  Description for feature X task

---
*Auto-generated by Ralph Dark Factory*
""")

    # Create temp state directory and file
    state_dir = tmp_path / "state"
    state_dir.mkdir()
    state_file = state_dir / "retry_state.json"
    state_file.write_text("{}")

    # Patch IMPLEMENTATION_PLAN path and state file
    with patch("src.plan.IMPLEMENTATION_PLAN", plan_file), \
         patch("src.ralph.SCENARIOS_DIR", tmp_path / "scenarios"):
        # Also patch the state manager to use temp state
        with patch("harness.state_manager.STATE_DIR", state_dir), \
             patch("harness.state_manager.RETRY_STATE_FILE", state_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            yield ralph


@pytest.fixture
def ralph_multitask(tmp_path, temp_signal_path, clean_state):
    """Create Ralph with multiple tasks for testing spin on specific task."""
    from src.ralph import Ralph

    plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
    plan_file.write_text("""# Implementation Plan: Multi-task Test

## Tasks

- [x] **Completed Task** (T001)
  Already done
- [ ] **Failing Task** (T002)
  This task keeps failing
- [ ] **Future Task** (T003)
  Not reached yet

---
*Auto-generated by Ralph Dark Factory*
""")

    # Create temp state directory and file
    state_dir = tmp_path / "state"
    state_dir.mkdir()
    state_file = state_dir / "retry_state.json"
    state_file.write_text("{}")

    with patch("src.plan.IMPLEMENTATION_PLAN", plan_file), \
         patch("src.ralph.SCENARIOS_DIR", tmp_path / "scenarios"):
        with patch("harness.state_manager.STATE_DIR", state_dir), \
             patch("harness.state_manager.RETRY_STATE_FILE", state_file):
            ralph = Ralph(project_path=str(tmp_path))
            ralph.load_plan()
            yield ralph


class TestSpinningDetection:
    """Tests for TC-03: Spinning detection after 5 consecutive failures."""

    def test_fifth_failure_triggers_spinning_signal(
        self, ralph_with_task, temp_signal_path
    ):
        """When Ralph processes the 5th failure signal, spinning signal is written."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task
            task = ralph.get_current_task()
            assert task.id == "T001"

            # Simulate 5 consecutive failures
            for retry_num in range(1, 6):
                # Write fail signal
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

                # After the 5th failure (retry_num == 5), spinning should be triggered
                if retry_num == 5:
                    # Verify spinning signal was written
                    assert temp_signal_path.exists()
                    content = json.loads(temp_signal_path.read_text())
                    assert content["spinning"] is True
                    assert content["task"] == task.title
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_written_at_exactly_five_failures(
        self, ralph_with_task, temp_signal_path
    ):
        """Spinning signal is written when retry count reaches exactly 5."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task

            # Fail 4 times - no spinning yet
            for _ in range(4):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            # At 4 failures, should NOT have spinning signal yet
            content_4 = temp_signal_path.read_text()
            if content_4:
                parsed = json.loads(content_4)
                assert "spinning" not in parsed or parsed.get("spinning") is not True

            # 5th failure
            temp_signal_path.write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()

            # Now spinning signal should exist
            content = json.loads(temp_signal_path.read_text())
            assert content.get("spinning") is True
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_contains_task_description(
        self, ralph_with_task, temp_signal_path
    ):
        """Spinning signal contains the task's title/description."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task
            task = ralph.get_current_task()
            expected_task_name = task.title

            # Simulate 5 failures
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            content = json.loads(temp_signal_path.read_text())
            assert content["task"] == expected_task_name
            assert "Implement Feature X" in content["task"]
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_has_correct_structure(self, ralph_with_task, temp_signal_path):
        """Spinning signal has exactly { "spinning": true, "task": "..." }."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task

            # Trigger spinning with 5 failures
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            content = json.loads(temp_signal_path.read_text())

            # Should have exactly these keys
            assert set(content.keys()) == {"spinning", "task"}
            assert content["spinning"] is True
            assert isinstance(content["task"], str)

            # Should NOT have pass field
            assert "pass" not in content
            assert "done" not in content
        finally:
            Signal.SIGNAL_PATH = original_signal_path


class TestSpinningDetectionIntegration:
    """Integration tests for full spinning detection flow."""

    def test_spinning_detected_on_specific_task_not_others(
        self, ralph_multitask, temp_signal_path
    ):
        """Spinning detection applies to the specific task being retried."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_multitask

            # Should start at T002 (first pending task)
            task = ralph.get_current_task()
            assert task.id == "T002"

            # Simulate 5 failures on T002
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            # Spinning signal should reference T002's description
            content = json.loads(temp_signal_path.read_text())
            assert "Failing Task" in content["task"]
            assert "Completed Task" not in content["task"]
            assert "Future Task" not in content["task"]
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_not_leaked_to_harness(
        self, ralph_with_task, temp_signal_path
    ):
        """Spinning signal doesn't leak which scenario failed or error details."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task

            # Trigger spinning
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            content_str = temp_signal_path.read_text()
            content = json.loads(content_str)

            # Should not contain error details
            forbidden = ["error", "reason", "detail", "assertion", "failed", "scenario", "T002"]
            for word in forbidden:
                # Allow the word in task name only if it's part of "Failing Task"
                if word in content_str.lower():
                    assert word in content.get("task", "")

            # Only spinning and task should be present
            assert set(content.keys()) == {"spinning", "task"}
        finally:
            Signal.SIGNAL_PATH = original_signal_path


class TestOperatorNotification:
    """Tests for operator notification when spinning is detected."""

    def test_spinning_signal_file_created_for_operator(
        self, ralph_with_task, temp_signal_path
    ):
        """Spinning signal file is created for operator to detect."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task

            # Trigger spinning
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            # File should exist for operator to detect
            assert temp_signal_path.exists()
            assert temp_signal_path.is_file()
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_is_valid_json(self, ralph_with_task, temp_signal_path):
        """Spinning signal is valid JSON that operator can parse."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task

            # Trigger spinning
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            # Should be parseable as JSON
            content = json.loads(temp_signal_path.read_text())
            assert isinstance(content, dict)
            assert "spinning" in content
        finally:
            Signal.SIGNAL_PATH = original_signal_path

    def test_spinning_signal_read_back_works(self, ralph_with_task, temp_signal_path):
        """Spinning signal can be read back using Signal.read()."""
        original_signal_path = Signal.SIGNAL_PATH
        Signal.SIGNAL_PATH = temp_signal_path

        try:
            ralph = ralph_with_task
            task_title = ralph.get_current_task().title

            # Trigger spinning
            for _ in range(5):
                temp_signal_path.write_text('{"pass": false}')
                ralph.load_signal()
                ralph.process_signal()

            # Read back using Signal.read()
            signal = Signal.read()
            assert signal.spinning is True
            assert signal.task == task_title
            assert signal.pass_result is None  # spinning signals don't have pass field
        finally:
            Signal.SIGNAL_PATH = original_signal_path
