"""Tests for Spinning Signal (TC-03 from Section 4).

Scenario: Spinning signal (TC-03 from Section 4)
Given Ralph is retrying the same task repeatedly
When the retry count exceeds the spinning threshold (default: 5)
Then /tmp/ralph-scenario-result.json contains { "spinning": true, "task": "task-name" }
And the operator is notified to intervene

This test verifies the core scenario: when Ralph spins, the signal file contains
the correct spinning signal format.
"""

import json
from pathlib import Path
from unittest.mock import patch

import pytest

from src.signal import Signal


@pytest.fixture
def isolated_ralph(tmp_path):
    """Create an isolated Ralph instance with its own state and signal files."""
    plan_file = tmp_path / "IMPLEMENTATION_PLAN.md"
    plan_file.write_text("""# Implementation Plan: Test Project

## Tasks

- [ ] **Implement Feature X** (T001)
  Description for feature X task

---
*Auto-generated by Ralph Dark Factory*
""")

    signal_path = tmp_path / "ralph-scenario-result.json"
    state_file = tmp_path / "retry_state.json"

    # Import here to avoid circular imports
    import src.ralph
    
    # Patch all necessary paths
    with patch("src.plan.IMPLEMENTATION_PLAN", plan_file):
        with patch("harness.state_manager.RETRY_STATE_FILE", state_file):
            # Create Ralph instance inside patch context
            ralph = src.ralph.Ralph(project_path=str(tmp_path))
            # Load plan inside patch context
            ralph.load_plan()
            
            # Now patch Signal path and yield
            original_signal_path = Signal.SIGNAL_PATH
            Signal.SIGNAL_PATH = signal_path
            
            yield ralph
            
            # Cleanup
            Signal.SIGNAL_PATH = original_signal_path


class TestSpinningSignalTC03Section4:
    """TC-03 from Section 4: Core spinning signal verification."""

    def test_spinning_signal_written_when_threshold_exceeded(self, isolated_ralph):
        """When retry count exceeds threshold, signal contains spinning=true and task name."""
        ralph = isolated_ralph
        task = ralph.get_current_task()
        
        # Simulate 5 consecutive failures (threshold is 5)
        for i in range(1, 6):
            # Write fail signal
            signal_path = Signal._get_signal_path()
            signal_path.write_text('{"pass": false}')
            
            # Ralph loads signal and processes it
            ralph.load_signal()
            ralph.process_signal()
            
            # After 5th failure, should trigger spinning
            if i == 5:
                signal_content = signal_path.read_text()
                result = json.loads(signal_content)
                assert result.get("spinning") is True, f"Expected spinning=true after {i} failures"
                assert "task" in result, "Spinning signal should contain task name"

    def test_spinning_signal_has_correct_format(self, isolated_ralph):
        """Spinning signal has exactly { 'spinning': true, 'task': '...' }."""
        ralph = isolated_ralph
        task = ralph.get_current_task()
        expected_task = task.title
        
        # Trigger spinning with 5 failures
        for _ in range(5):
            Signal._get_signal_path().write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
        
        # Read the signal file
        signal_path = Signal._get_signal_path()
        content = json.loads(signal_path.read_text())
        
        # Verify structure
        assert set(content.keys()) == {"spinning", "task"}, (
            f"Expected exactly keys {{'spinning', 'task'}}, got {set(content.keys())}"
        )
        assert content["spinning"] is True
        assert content["task"] == expected_task

    def test_spinning_signal_contains_task_name_not_id(self, isolated_ralph):
        """Spinning signal contains the task title/description, not just the ID."""
        ralph = isolated_ralph
        task = ralph.get_current_task()
        
        # Trigger spinning
        for _ in range(5):
            Signal._get_signal_path().write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
        
        content = json.loads(Signal._get_signal_path().read_text())
        
        # Task name should be descriptive, not just "T001"
        assert content["task"] == "Implement Feature X"
        assert "T001" not in content["task"]

    def test_operator_notification_ready(self, isolated_ralph):
        """Spinning signal file is ready for operator to detect and intervene."""
        ralph = isolated_ralph
        
        # Trigger spinning
        for _ in range(5):
            Signal._get_signal_path().write_text('{"pass": false}')
            ralph.load_signal()
            ralph.process_signal()
        
        signal_path = Signal._get_signal_path()
        
        # File should exist and be valid JSON
        assert signal_path.exists(), "Signal file should exist after spinning detected"
        content = json.loads(signal_path.read_text())
        assert content.get("spinning") is True, "Operator should be able to detect spinning=true"
