"""Plan generation from specs.

This module reads specs from specs/*.md and generates IMPLEMENTATION_PLAN.md.
It does NOT read from scenarios/ (filesystem isolation).
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List

SPECS_DIR = Path("specs")
IMPLEMENTATION_PLAN = Path("IMPLEMENTATION_PLAN.md")
TASKS_DIR = Path(".orch/tasks")


@dataclass
class Task:
    """Represents a task in the implementation plan."""

    id: str
    title: str
    description: str
    status: str = "pending"
    retry_count: int = 0

    def to_markdown(self) -> str:
        """Convert task to markdown format."""
        checkbox = "[x]" if self.status == "done" else "[ ]"
        return f"- [{checkbox}] **{self.title}** ({self.id})\n  {self.description}"


@dataclass
class ImplementationPlan:
    """Represents the implementation plan."""

    project_name: str
    tasks: List[Task] = field(default_factory=list)

    def add_task(self, title: str, description: str) -> Task:
        """Add a task to the plan."""
        task_id = f"T{len(self.tasks) + 1:03d}"
        task = Task(id=task_id, title=title, description=description)
        self.tasks.append(task)
        return task

    def to_markdown(self) -> str:
        """Convert plan to markdown format."""
        lines = [
            f"# Implementation Plan: {self.project_name}",
            "",
            "## Tasks",
            "",
        ]
        for task in self.tasks:
            lines.append(task.to_markdown())
        lines.append("")
        lines.append("---")
        lines.append("*Auto-generated by Ralph Dark Factory*")
        return "\n".join(lines)

    def get_pending_tasks(self) -> List[Task]:
        """Get all pending tasks."""
        return [t for t in self.tasks if t.status == "pending"]

    def get_current_task(self) -> Task:
        """Get the first pending task."""
        pending = self.get_pending_tasks()
        return pending[0] if pending else None

    def mark_done(self, task_id: str) -> None:
        """Mark a task as done."""
        for task in self.tasks:
            if task.id == task_id:
                task.status = "done"
                break

    def increment_retry(self, task_id: str) -> int:
        """Increment retry count for a task and return new count."""
        for task in self.tasks:
            if task.id == task_id:
                task.retry_count += 1
                return task.retry_count
        return 0


def parse_spec_file(filepath: Path) -> List[Task]:
    """Parse a spec file and extract tasks."""
    tasks = []
    content = filepath.read_text()

    # Extract feature name
    feature_match = re.search(r"#\s*Feature:\s*(.+)", content)
    project_name = feature_match.group(1).strip() if feature_match else "Unnamed Project"

    # Extract scenario titles and descriptions
    scenario_pattern = re.compile(r"##\s*Scenario:\s*(.+?)(?=\n##|\Z)", re.DOTALL)
    for i, match in enumerate(scenario_pattern.finditer(content)):
        title = match.group(1).strip().split("\n")[0]
        # Extract Given/When/Then for description
        given_when_then = re.findall(r"(Given|When|Then|And)\s+(.+?)(?=\n(?:Given|When|Then|And|$))", match.group(1), re.DOTALL)
        if given_when_then:
            desc_parts = [f"{g}: {d.strip()}" for g, d in given_when_then[:3]]
            description = "; ".join(desc_parts)
        else:
            description = title

        task_id = f"T{i + 1:03d}"
        tasks.append(Task(id=task_id, title=title, description=description))

    return tasks, project_name


def generate_plan() -> ImplementationPlan:
    """Generate implementation plan from all spec files.

    This function reads specs/*.md but does NOT read scenarios/
    (filesystem isolation enforced).
    """
    plan = ImplementationPlan(project_name="Ralph Dark Factory")

    # Check if specs directory exists and is readable
    if not SPECS_DIR.exists():
        return plan

    # Read all spec files
    spec_files = sorted(SPECS_DIR.glob("*.md"))

    for spec_file in spec_files:
        try:
            tasks, project_name = parse_spec_file(spec_file)
            if project_name and plan.project_name == "Ralph Dark Factory":
                plan.project_name = project_name
            for task in tasks:
                plan.tasks.append(task)
        except Exception:
            continue

    return plan


def save_plan(plan: ImplementationPlan) -> None:
    """Save the implementation plan to IMPLEMENTATION_PLAN.md."""
    content = plan.to_markdown()
    IMPLEMENTATION_PLAN.write_text(content)


def load_plan() -> ImplementationPlan:
    """Load the implementation plan from IMPLEMENTATION_PLAN.md."""
    if not IMPLEMENTATION_PLAN.exists():
        return generate_plan()

    content = IMPLEMENTATION_PLAN.read_text()
    plan = ImplementationPlan(project_name="Unknown")

    # Parse existing plan
    current_task = None
    for line in content.split("\n"):
        task_match = re.match(r"- \[([ x])\] \*\*([^*]+)\*\* \((T\d+)\)", line)
        if task_match:
            status = "done" if task_match.group(1) == "x" else "pending"
            title = task_match.group(2).strip()
            task_id = task_match.group(3)
            current_task = Task(id=task_id, title=title, status=status)
            plan.tasks.append(current_task)
        elif current_task and line.strip().startswith("- [ ]") is False and line.startswith("  "):
            current_task.description += " " + line.strip()

    return plan
